export const companies = [
  {
    id: 1,
    company_name: "Facebook",
    company_logo: "https://devshubbd.com/images/facebook.png",
    company_url: "https://www.facebook.com/btebresultshub",
    company_linkedin: "https://www.linkedin.com/company/facebook/",
    company_facebook: "https://www.facebook.com/facebook",
    // company_careers_url: "https://www.facebook.com/careers/",
    company_email: "xxx@gmail.com",
    work_type: "On-site",
    hire_freshers: true,
    hire_interns: false,
    office_location: "Menlo Park, California, United States",
    established: "since 2004",
    total_employees: "100 - 500",
    primary_tech_stack: ["React", "React Native", "GraphQL", "Relay"],
    current_hiring_role: "Software Engineer",
    company_description: `Facebook is an American online social media and social networking service company based in Menlo Park, California. Its website was launched on February 4, 2004, by Mark Zuckerberg, along with fellow Harvard College students and roommates Eduardo Saverin, Andrew McCollum, Dustin Moskovitz, and Chris Hughes.`,
  },
  {
    id: 2,
    company_name: "Google",
    company_logo: "https://devshubbd.com/images/google.png",
    company_url: "https://www.google.com/",
    company_linkedin: "https://www.linkedin.com/company/google/",
    company_facebook: "https://www.facebook.com/Google",
    company_careers_url: "https://careers.google.com/",
    work_type: "Hybrid",
    hire_freshers: true,
    hire_interns: true,
    office_location: "Mountain View, California, United States",
    established: "since 1998",
    total_employees: "1000 - 5000",
    primary_tech_stack: ["Angular", "React", "Vue", "Node", "Express"],
    current_hiring_role: "Software Engineer",
    company_description: `Google LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware. It is considered one of the Big Five companies in the U.S. information technology industry, alongside Amazon, Facebook, Apple, and Microsoft.`,
  },
  {
    id: 3,
    company_name: "Amazon",
    company_logo: "https://devshubbd.com/images/amazon.png",
    company_url: "https://www.amazon.com/",
    company_linkedin: "https://www.linkedin.com/company/amazon/",
    company_facebook: "https://www.facebook.com/Amazon",
    company_careers_url: "https://www.amazon.jobs/",
    work_type: "Remote",
    hire_freshers: true,
    hire_interns: true,
    office_location: "Seattle, Washington, United States",
    established: "since 1994",
    total_employees: "1000 - 5000",
    primary_tech_stack: ["React", "React Native", "GraphQL", "Relay"],
    current_hiring_role: "Software Engineer",
    company_description: `Amazon.com, Inc. is an American multinational technology company based in Seattle, Washington, which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence. It is one of the Big Five companies in the U.S. information technology industry, along with Google, Apple, Microsoft, and Facebook.`,
  },
  {
    id: 4,
    company_name: "Apple",
    company_logo: "https://devshubbd.com/images/apple.png",
    company_url: "https://www.apple.com/",
    company_linkedin: "https://www.linkedin.com/company/apple/",
    company_facebook: "https://www.facebook.com/Apple",
    company_careers_url: "https://www.apple.com/jobs/",
    work_type: "On-site",
    hire_freshers: true,
    hire_interns: true,
    office_location: "Cupertino, California, United States",
    established: "since 1976",
    total_employees: "1000 - 5000",
    primary_tech_stack: ["React", "React Native", "GraphQL", "Relay"],
    current_hiring_role: "Software Engineer",
    company_description: `Apple Inc. is an American multinational technology company that specializes in consumer electronics, computer software, and online services. Apple is the world's largest technology company by revenue and, since January 2021, the world's most valuable company.`,
  },
  {
    id: 5,
    company_name: "Microsoft",
    company_logo: "https://devshubbd.com/images/microsoft.png",
    company_url: "https://www.microsoft.com/",
    company_linkedin: "https://www.linkedin.com/company/microsoft/",
    company_facebook: "https://www.facebook.com/Microsoft",
    company_careers_url: "https://careers.microsoft.com/",
    work_type: "Hybrid",
    hire_freshers: true,
    hire_interns: true,
    office_location: "Redmond, Washington, United States",
    established: "since 1975",
    total_employees: "1000 - 5000",
    primary_tech_stack: ["React", "React Native", "GraphQL", "Relay"],
    current_hiring_role: "Software Engineer",
    company_description: `Microsoft Corporation is an American multinational technology company with headquarters in Redmond, Washington. It develops, manufactures, licenses, supports, and sells computer software, consumer electronics, personal computers, and related services.`,
  },
  {
    id: 6,
    company_name: "Netflix",
    company_logo: "https://devshubbd.com/images/netflix.png",
    company_url: "https://www.netflix.com/",
    company_linkedin: "https://www.linkedin.com/company/netflix/",
    company_facebook: "https://www.facebook.com/Netflix",
    company_careers_url: "https://jobs.netflix.com/",
    work_type: "Remote",
    hire_freshers: true,
    hire_interns: true,
    office_location: "Los Gatos, California, United States",
    established: "since 1997",
    total_employees: "1000 - 5000",
    primary_tech_stack: ["React", "React Native", "GraphQL", "Relay"],
    current_hiring_role: "Software Engineer",
    company_description: `Netflix, Inc. is an American over-the-top content platform and production company headquartered in Los Gatos, California. Netflix was founded in 1997 by Reed Hastings and Marc Randolph in Scotts Valley, California.`,
  },
  {
    id: 7,
    company_name: "Twitter",
    company_logo: "https://devshubbd.com/images/twitter.png",
    company_url: "https://www.twitter.com/",
    company_linkedin: "https://www.linkedin.com/company/twitter/",
    company_facebook: "https://www.facebook.com/Twitter",
    company_careers_url: "https://careers.twitter.com/",
    work_type: "Remote",
    hire_freshers: true,
    hire_interns: true,
    office_location: "San Francisco, California, United States",
    established: "since 2006",
    total_employees: "1000 - 5000",
    primary_tech_stack: ["React", "React Native", "GraphQL", "Relay"],
    current_hiring_role: "Software Engineer",
    company_description: `Twitter is an American microblogging and social networking service on which users post and interact with messages known as "tweets". Registered users can post, like, and retweet tweets, but unregistered users can only read them.`,
  },
  {
    id: 8,
    company_name: "Uber",
    company_logo: "https://devshubbd.com/images/uber.png",
    company_url: "https://www.uber.com/",
    company_linkedin: "https://www.linkedin.com/company/uber/",
    company_facebook: "https://www.facebook.com/Uber",
    company_careers_url: "https://www.uber.com/us/en/careers/",
    work_type: "Remote",
    hire_freshers: true,
    hire_interns: true,
    office_location: "San Francisco, California, United States",
    established: "since 2009",
    total_employees: "1000 - 5000",
    primary_tech_stack: ["React", "React Native", "GraphQL", "Relay"],
    current_hiring_role: "Software Engineer",
    company_description: `Uber Technologies, Inc., commonly known as Uber, is an American technology company. Its services include ride-hailing, food delivery, package delivery, couriers, and a freight transportation. Uber is based in San Francisco and has operations in over 900 metropolitan areas worldwide.`,
  },
  {
    id: 9,
    company_name: "Airbnb",
    company_logo: "https://devshubbd.com/images/airbnb.png",
    company_url: "https://www.airbnb.com/",
    company_linkedin: "https://www.linkedin.com/company/airbnb/",
    company_facebook: "https://www.facebook.com/Airbnb",
    company_careers_url: "https://careers.airbnb.com/",
    work_type: "Remote",
    hire_freshers: true,
    hire_interns: true,
    office_location: "San Francisco, California, United States",
    established: "since 2008",
    total_employees: "1000 - 5000",
    primary_tech_stack: ["React", "React Native", "GraphQL", "Relay"],
    current_hiring_role: "Software Engineer",
    company_description: `Airbnb, Inc. is an American vacation rental online marketplace company based in San Francisco, California. Airbnb maintains and hosts a marketplace, accessible to consumers on its website or via a mobile app.`,
  },
  {
    id: 10,
    company_name: "Slack",
    company_logo: "https://devshubbd.com/images/slack.png",
    company_url: "https://www.slack.com/",
    company_linkedin: "https://www.linkedin.com/company/slack/",
    company_facebook: "https://www.facebook.com/Slack",
    company_careers_url: "https://slack.com/careers",
    work_type: "Remote",
    hire_freshers: true,
    hire_interns: true,
    office_location: "San Francisco, California, United States",
    established: "since 2009",
    total_employees: "1000 - 5000",
    primary_tech_stack: ["React", "React Native", "GraphQL", "Relay"],
    current_hiring_role: "Software Engineer",
    company_description: `Slack Technologies, Inc. is an American international software company founded in 2009 in Vancouver, British Columbia, Canada. The company is headquartered in San Francisco, California.`,
  },
];
