import { Inter as FontSans } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "../../components/theme-provider";
import "../globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "dashboard | devjobsbd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={`${fontSans.className} min-w[350px]`}>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <NextTopLoader
          color="#1E3A8A"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
        />
        {children}
      </ThemeProvider>
    </div>
  );
}
